title: Mohammed Zoheb Jahagirdar
description: AI-LLM/MLOps Engineer | AWS Certified | GenAI Enthusiast
theme: minima
author: Mohammed Zoheb Jahagirdar

github_username: zohebj007
linkedin_username: Mohammed-zoheb-jahagirdar
email: jahagirdarzoheb@gmail.com
